– Due to UEBuildFramework deprecation in 4.22: UEBuildFramework renamed to Framework – Error CS0151(switch to if-else), thanks to @GloryOfNight – Replaced plugin source files in demo to simlink